`date` date NOT NULL COMMENT '日期',
`sid` tinyint(4) NOT NULL DEFAULT '0',
`channel_id` int(11) NOT NULL COMMENT '渠道ID',
`register_num` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '注册人数',
`tow_day_money` decimal(12,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '次日ltv消费',
`three_day_money` decimal(12,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '三日ltv消费',
`four_day_money` decimal(12,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '四日ltv消费',
`five_day_money` decimal(12,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '五日ltv消费',
`six_day_money` decimal(12,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '六日ltv消费',
`seven_day_money` decimal(12,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '七日ltv消费',
`eight_day_money` decimal(12,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '八日ltv消费',
`nine_day_money` decimal(12,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '九日ltv消费',
`ten_day_money` decimal(12,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '十日ltv消费',
`fifteen_day_money` decimal(12,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '十五日ltv消费',